/*
Guestbank database must be empty.
*/
ALTER TABLE CLIENT
ADD 
(branchcode NUMBER(3, 0) NOT NULL);
	

ALTER TABLE CLIENT
MODIFY
(username VARCHAR2(100));

ALTER TABLE ADMINS ADD(branchcode NUMBER(3, 0) NOT NULL);

ALTER TABLE ADMINS
MODIFY
(username VARCHAR2(100));

ALTER TABLE USERS
MODIFY
(username VARCHAR2(100));